# 1. URL de conexión a la base de datos local
spring.datasource.url=jdbc:mysql://localhost:3306/bodega_db?serverTimezone=UTC&useSSL=false

# 2. Credenciales de tu MySQL (Cambia esto según la conf local)
spring.datasource.username=root
spring.datasource.password=admin

# 3. Driver de MySQL y Dialecto para Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Estrategia de creación de tablas (La magia de JPA)
spring.jpa.hibernate.ddl-auto=update

# 5. Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true